#Delete an Event
DELETE http://127.0.0.1:8000/events/2
Accept: application/json
#Authorization: Bearer <token>
###

#Invite Users
POST http://127.0.0.1:8000/events/1/invite/2
Content-Type: application/json
#Authorization: Bearer <token>
###


###
#Get Events You Are Invited To
GET http://127.0.0.1:8000/events/invited
Accept: application/json
#Authorization: Bearer <token>

###
#Get Your Organized Events
GET http://127.0.0.1:8000/events/organized
Accept: application/json
#Authorization: Bearer <token>
###
#signup
POST http://127.0.0.1:8000/auth/signup
Content-Type: application/json

{
  "email": "noran14@example.com",
  "password": "mysecurepassword"
}

###
#login
###
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "noran14@example.com",
  "password": "mysecurepassword"
}


###
# Test your FastAPI endpoints
GET http://127.0.0.1:8000/event
Accept: application/json

###
#create event
POST http://127.0.0.1:8000/events/create
Content-Type: application/json
#Authorization: Bearer <token>

{
    "title": "Meeting",
    "date": "2025-01-21",
    "time": "14:00:00",
    "location": "Office",
    "description": "Planning meeting"
}







